const en = {
    moves: 'Moves: ',
    timeControl: 'Time Control',
    time: 'Time',
    increment: 'Increment',
    timePlayer1: 'Time for player 1',
    timePlayer2: 'Time for player 2',
    newTimeControl: 'New time control',
    name: 'Name',
    settings: 'Settings',
    seconds: 'seconds',
    minutes: 'minutes',
    theme: 'Theme: ',
    language: 'Language: ',
    catalan: 'Catalan',
    spanish: 'Spanish',
    english: 'English',
    light: 'Light',
    dark: 'Dark',
    chooseLanguage: 'Choose a language',
    chooseTheme: 'Choose a theme',
    darkWithBlue: 'Dark (Blue)',
    darkWithRed: 'Dark (Red)',
    darkWithBrown: 'Dark (Brown)',
    darkWithGreen: 'Dark (Green)',
    lightWithGreen: 'Light (Green)',
    lightWithOrange: 'Light (Orange)',
    differentTimes: 'Do you want to set different times for each player?',
    FDescription: 'The players recieve the full amount of increment at the end of each turn.',
    BDescription: 'The players recieve the used amount of increment at the end of each turn.',
    DDescription: "The player's clock doesn't start until the delay period is finished.",
    save: 'Save',
    requiredField: "This field is required.",
    timeFormatError: "Time must be in mm:ss format.",
    incrementError: "The increment must be an integer number.",
    editTime: "Edit time",
    warning: "Warning",
    deleteTimeDescription: "Are you sure you want to delete this time control?",
    yes: 'Yes',
    no: 'No',
    cancel: 'Cancel',
    delete: 'Delete',
    deleteAllDescription: "Are you sure you want to delete all the selected time controls?",
    deleteAllError: "You cannot delete all time controls. Must have at least one."
}

export default en
