const es = {
    moves: 'Movimientos: ',
    timeControl: 'Controles de tiempo',
    time: 'Tiempo',
    increment: 'Incremento',
    timePlayer1: 'Tiempo para el jugador 1',
    timePlayer2: 'Tiempo para el jugador 2',
    newTimeControl: 'Nuevo control de tiempo',
    name: 'Nombre',
    settings: 'Ajustes',
    seconds: 'segundos',
    minutes: 'minutos',
    theme: 'Tema: ',
    language: 'Idioma: ',
    catalan: 'Catalán',
    spanish: 'Castellano',
    english: 'Inglés',
    light: 'Claro',
    dark: 'Oscuro',
    chooseLanguage: 'Escoje un idioma',
    chooseTheme: 'Escoje un tema',
    darkWithBlue: 'Oscuro (Azul)',
    darkWithRed: 'Oscuro (Rojo)',
    darkWithBrown: 'Oscuro (Marrón)',
    darkWithGreen: 'Oscuro (Verde)',
    lightWithGreen: 'Claro (Verde)',
    lightWithOrange: 'Claro (Naranja)',
    differentTimes: '¿Quieres poner tiempos diferentes por jugador?',
    FDescription: 'Los jugadores reciben la cantidad entera del incremento al final de cada turno.',
    BDescription: 'Los jugadores reciben la cantidad usada del incremento al final de cada turno.',
    DDescription: 'El reloj del jugador no empieza a contar hasta que pasa el periodo de delay.',
    save: 'Guardar',
    requiredField: "Este campo es obligatorio.",
    timeFormatError: "El tiempo tiene que estar en el formato mm:ss.",
    incrementError: "El incremento tiene que ser un número entero.",
    editTime: "Editar tiempo",
    warning: "Atención",
    deleteTimeDescription: "¿Estás seguro de que quieres eliminar este control de tiempo?",
    yes: 'Sí',
    no: 'No',
    cancel: 'Cancelar',
    delete: 'Eliminar',
    deleteAllDescription: "¿Estás seguro de que quieres eliminar los controles de tiempo seleccionados?",
    deleteAllError: "No se pueden eliminar todos los controles de tiempo. Debe haber mínimo uno.",
    suggestions: "Cualquier sugerencia a agusdac.dev@gmail.com."
}

export default es
